### PR TITLE
Update to Keycloak Gatekeeper 8.0.1

### PR DESCRIPTION
**Pull request by phxql**
**Description of the change**

Updates Keycloak Gatekeeper to the 8.0.1 release

**Benefits**

Bugfixes and features from upstream Keycloak Gatekeeper

**Possible drawbacks**

none.

**Applicable issues**

none.

**Additional information**

none.

See issue #6

### CODE REVIEW

**Comment by juan131** [comment]
Hi @phxql 

Thanks so much for the contribution!

We're tracking releases from the link below:

- https://github.com/keycloak/keycloak-gatekeeper/releases

As you can see the latest release there is **2.3.0**. Where did you obtain the version **8.0.1** from?

On the other hand, please note that we do not accept any binary on our docker images that hasn't been compiled by our internal tools or the upstream provider. 
In the case of Keycloak Gatekeeper, we download the source code and compile the binaries.

**Comment by juan131** [comment]
I just noticed they're not doing releases but creating "tags" instead. We should be tracking:

- https://github.com/keycloak/keycloak-gatekeeper/tags

Instead of:

- https://github.com/keycloak/keycloak-gatekeeper/releases

Let me try to fix this

**Comment by phxql** [comment]
Yes, i stumbled in the same trap. The keycloak gatekeeper from the [official Keycloak download page](https://www.keycloak.org/downloads.html) seem to reference the tags.

**Comment by juan131** [comment]
Hi @phxql 

We fixed the issue in our version tracking system, and a new version was automatically released by our release pipeline.

I'm closing this PR since it's not necessary anymore. Thanks so much for noticing us about this!

**Pull request closed without merging**
